## Introduction to PyTorch

### Tensors

It turns out neural network computations are just a bunch of linear algebra operations on tensors which are a generalization of matrices. The fundamental data structure for neural networks are tensorrs and PyTorch is built around tensors

In [1]:
#Import pytorch
import torch

In [2]:
def activation(x):
    """
    Sigmoid activation function
    x: torch.Tensor 
    """
    return 1/(1+torch.exp(-x))

In [5]:
#Let's generate some data
#Set random seed
torch.manual_seed(7)

#Create features, givin tuple as size, randn (random from normal variable)
features = torch.randn((1,5)) #1 row, 5 cols

#Create weights for our data
weights = torch.rand_like(features)

#Create the bias term
bias = torch.randn((1,1)) #

In [13]:
#Let's calculate the output of our neural network

y = activation(torch.sum(features * weights) + bias)
print(y)

y = activation((features * weights).sum() + bias)
print(y)
                

tensor([[0.6140]])
tensor([[0.6140]])


In [22]:
#Matrix multiplication through modern libraries
#Note using the tensor method you have to take care of having
#The correct dimensions. Let's see.

#Run time error, it complains about dimensions 
#mult = torch.mm(weights, features)

print(weights.shape)
print(features.shape)

#We need [n,m]x[m,n]! Let's reshape the vectors

torch.Size([1, 5])
torch.Size([1, 5])


In [37]:
# features.resize_(features.shape[1], features.shape[0])
# features.shape
# #But, better to creare a new vector with different shape


torch.Size([1, 5])

In [46]:
featuresT = features.view(features.shape[1], features.shape[0])
print(featuresT.shape)

torch.Size([5, 1])


In [44]:
#Now we are ready to perform our multiplication
y = activation(torch.sum(torch.mm(weights,featuresT)) + bias)
y

tensor([[0.6140]])

### Numpy to Torch and Back

In [56]:
import numpy as np

In [57]:
#Let's create a numpy array adn try to make it a torch tensor
a = np.random.rand(4,3)
print(a)

[[0.39476001 0.90535771 0.46747765]
 [0.97629124 0.04471822 0.85189157]
 [0.76437726 0.22582564 0.42229591]
 [0.65479359 0.56546289 0.39972986]]


In [58]:
b = torch.from_numpy(a)
print(b)

#Simple, isn't it?

tensor([[0.3948, 0.9054, 0.4675],
        [0.9763, 0.0447, 0.8519],
        [0.7644, 0.2258, 0.4223],
        [0.6548, 0.5655, 0.3997]], dtype=torch.float64)


In [59]:
#We can go also back to numpy
c = b.numpy()
print(c)

[[0.39476001 0.90535771 0.46747765]
 [0.97629124 0.04471822 0.85189157]
 [0.76437726 0.22582564 0.42229591]
 [0.65479359 0.56546289 0.39972986]]


#### REMINDER
The memory is shared between numpy array and pytorch, so if you change the values ***in_place*** of one object, the other will change as well!

In [60]:
print(b.mul_(2))
print(c)

tensor([[0.7895, 1.8107, 0.9350],
        [1.9526, 0.0894, 1.7038],
        [1.5288, 0.4517, 0.8446],
        [1.3096, 1.1309, 0.7995]], dtype=torch.float64)
[[0.78952002 1.81071542 0.9349553 ]
 [1.95258247 0.08943643 1.70378314]
 [1.52875452 0.45165129 0.84459183]
 [1.30958718 1.13092577 0.79945971]]
